### ISSUE TITLE
Can't focus using GUI or terminal

### ISSUE THREAD

**Issue by jagdpanz** [moof-src/ArduCamFocus#8]
I have installed all prerequisites, but in logfile I still see the same errors: 

OSError: [Errno 121] Remote I/O error
2021-02-04 19:41:34,743 - octoprint.plugins.ArduCamFocus - INFO - setting FOCUS to 110
2021-02-04 19:41:34,744 - octoprint.util.comm - ERROR - Error while processing hook ArduCamFocus for phase queuing and command ARDUCAMFOCUS:
Traceback (most recent call last):
  File "/home/pi/oprint/lib/python3.7/site-packages/octoprint/util/comm.py", line 4605, in _process_atcommand_phase
    hook(self, phase, atcommand, parameters, tags=tags)
  File "/home/pi/oprint/lib/python3.7/site-packages/octoprint/util/__init__.py", line 1890, in wrapper
    return f(*args, **kwargs)
  File "/home/pi/oprint/lib/python3.7/site-packages/ArduCamFocus/__init__.py", line 98, in processAtCommand
    self.focus(self.current_focus + int(parameters))
  File "/home/pi/oprint/lib/python3.7/site-packages/ArduCamFocus/__init__.py", line 85, in focus
    self.bus.write_byte_data(0xc, data1, data2)

**Comment by moof-src** [comment]
I suppose that could happen if the i2c connection was bad or the camera
can’t communicate, or the camera is the wrong model.  have you tried
replacing the cable?

**Comment by jagdpanz** [comment]
Thanks for your quick response! I really appreciate it.
It's even more funny - I was sure that autofocus works also in "idle" mode - but it looks like I can play with AF during the printing process only. Is this expected ?

**Comment by moof-src** [comment]
it works while you are connected to printer.

**Comment by jneilliii** [comment]
I too am getting this error.

```
2021-04-24 07:45:39,215 - octoprint.plugins.ArduCamFocus - INFO - setting FOCUS to 110
2021-04-24 07:45:39,218 - octoprint.util.comm - ERROR - Error while processing hook ArduCamFocus for phase queuing and command ARDUCAMFOCUS:
Traceback (most recent call last):
  File "/home/pi/oprint/lib/python3.7/site-packages/octoprint/util/comm.py", line 4634, in _process_atcommand_phase
    hook(self, phase, atcommand, parameters, tags=tags)
  File "/home/pi/oprint/lib/python3.7/site-packages/octoprint/util/__init__.py", line 1941, in wrapper
    return f(*args, **kwargs)
  File "/home/pi/oprint/lib/python3.7/site-packages/ArduCamFocus/__init__.py", line 98, in processAtCommand
    self.focus(self.current_focus + int(parameters))
  File "/home/pi/oprint/lib/python3.7/site-packages/ArduCamFocus/__init__.py", line 85, in focus
    self.bus.write_byte_data(0xc, data1, data2)
OSError: [Errno 121] Remote I/O error
```

running under octopi 0.18 on a pi zero with OctoPrint 1.6.0.

**Comment by jneilliii** [comment]
maybe this could help...

https://stackoverflow.com/questions/52735862/getting-ioerror-errno-121-remote-i-o-error-with-smbus-on-python-raspberry-w

**Comment by moof-src** [comment]
Please see if my 0.0.6 prevents the IOError problems you've been seeing.

@jneilliii I didn't see your update before trying my own.  Let me know if this works.

**Comment by jneilliii** [comment]
Unfortunately it doesn't resolve the issue for me, still unable to control. I just saw reports on discord too of the same thing from another user (at least same error in the UI after your updates).

**Comment by jonasoh** [comment]
With some ArduCams, you need to use I2C bus 1 instead of 0. I guess these are the old cams with SCL/SDA over separate jumper cables as opposed to via the camera flex cable itself. Possibly this is the reason for some of the issues with GUI control.

On my setup with one of these older cameras, simply changing https://github.com/moof-src/ArduCamFocus/blob/adcecf81ddc6ccbbb0a7f4126a84d5c929187b63/ArduCamFocus/__init__.py#L17
to `			self.bus = smbus.SMBus(1)` was enough to enable focusing. 
 
Not sure what the best way would be to make this work on both types of cameras. For my purposes, I've just sent the data to both buses in order to be compatible with both, although I think that using bus 1 would work for both types actually (as long as i2c_arm overlay is loaded).

I could try to implement a fix for this issue to avoid having to maintain my edited version, but would appreciate input on what would be the best approach.

**Comment by jneilliii** [comment]
I would be willing to test, you mention separate jumper cables though, how are those wired/connected?

**Comment by jonasoh** [comment]
@jneilliii Well, I think that if you specifically get the Error 121 thing, then the problem is not with the I2C bus number. The camera I'm talking about is this one, not sure if they still sell it: 
<img width="167" alt="image" src="https://user-images.githubusercontent.com/6480370/119866673-92e62080-bf0c-11eb-99a9-ae4e9413a21b.png">

**Comment by jpkelly** [comment]
I had a similar issue and I was able to enable focus control by changing a  line in
`/home/pi/oprint/lib/python3.7/site-packages/ArduCamFocus/__init__.py`

I changed the line
`self.bus = smbus.SMBus(0)`
to
`self.bus = smbus.SMBus(10)`

I discovered the bus 10 by running
`ls /dev/i2c*`
and got
`/dev/i2c-0  /dev/i2c-1	/dev/i2c-10  /dev/i2c-11`

**Comment by moof-src** [comment]
Thanks for the update.  Please tell me which camera you have and the model
of your raspberry pi.  I have the ArduCam Motorized Focus Camera.  It does
not have any external connectors other than the ribbon cable that attaches
to the pi.

I bought mine on Amazon:

[image: image.png]
Arducam Auto Focus Pi Camera, Autofocus for Raspberry Pi Camera Module,
Motorized Focus Lens, Software Precise Manual Focus, OV5647 5MP 1080P.

I am running one on a Raspberry Pi 4 model b, and another one on a
Raspberry Pi 3 model b.

**Comment by jpkelly** [comment]
This is the camera I am using.
https://www.amazon.com/dp/B0953KHRYZ

It is on a Raspberry Pi 4
https://www.amazon.com/dp/B07TC2BK1X

Note I ran the following to check the bus.
`i2cdetect -y 10`
and got
```
     0  1  2  3  4  5  6  7  8  9  a  b  c  d  e  f
00:          -- -- -- -- -- -- -- -- -- 0c -- -- -- 
10: -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- 
20: -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- 
30: -- -- -- -- -- -- 36 -- -- -- -- -- -- -- -- -- 
40: -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- 
50: -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- 
60: -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- 
70: -- -- -- -- -- -- -- --   

```

`i2cdetect -y 0` 
Did not show any devices.

**Comment by jneilliii** [comment]
nice, this may actually fix my issue. Running i2cdetect -y 10 returned the same for me. Going to try your changes and see if I'm able to focus then.

**Comment by jneilliii** [comment]
I can confirm, I'm no longer getting errors with `self.bus = smbus.SMBus(10)`, but can't really tell from the stream if it's making much of a difference. @moof-src maybe it would be a good idea to make the bus number configurable via settings?

**Comment by moof-src** [comment]
I will do that.  I was wondering what is different in the setup that is
making your camera show up on a different bus.  I will update the install
instructions.  Please tell me the hardware you are using.  camera, model
number, pi, model number.  os.  thanks.

**Comment by jneilliii** [comment]
I'm using this arducam: https://www.amazon.com/gp/product/B07SN8GYGD/ref=ppx_yo_dt_b_search_asin_title?ie=UTF8&psc=1

connected on a pi zero w running octopi version 0.18.

**Comment by jonasoh** [comment]
Looks like Arducam themselves created a similar Octoprint plugin. They use either bus number 10 or 1:
https://github.com/ArduCAM/ArducamCameraControl/blob/e80c134bf2ffb1459f2042b6e928d85fb91a79cc/ArducamCameraControl/__init__.py#L27-L36

Interesting approach for finding the correct one...:
https://github.com/ArduCAM/ArducamCameraControl/blob/e80c134bf2ffb1459f2042b6e928d85fb91a79cc/ArducamCameraControl/__init__.py#L164-L180

**Comment by jneilliii** [comment]
Yeah, that plugin is in the process of being reviewed for the official repo.

**Comment by condraka** [comment]
My camera stopped working (have not used my system for a month)  after a couple of updates.
It was working fine not to long ago so something changed in the system.
I can also confirm that I had to change to bus 10 to get it back up and running.
Thanks...  jpkelly for the fix.  it's working again.
I'm using this camera on a Raspberry Pi 3B+
https://www.amazon.com/gp/product/B07SN8GYGD/ref=ppx_yo_dt_b_search_asin_title?ie=UTF8&psc=1

**Comment by markdconner** [comment]
> I'm using this arducam: https://www.amazon.com/gp/product/B07SN8GYGD/ref=ppx_yo_dt_b_search_asin_title?ie=UTF8&psc=1
> 
> connected on a pi zero w running octopi version 0.18.

I just got this camera for my OctoPi setup on a Pi 3 and OctoPrint v1.6.1 and had to apply the same fix to get it to work (make it SMBus(10)).

**Comment by thgnetworks** [comment]
I had the same issue as jpkelly and I too had to edit my \_\_init\_\_.py file to reflect the self.bus = smbus.SMBus(10)

It does not look like the source has been updated yet to reflect these cameras. I know it is frustrating to try to get this to work. I'm an experienced Linux pro and it was trivial for me to fix but novices would have a much more difficult time to get this fix implemented. Please update the source code to automatically check for the correct smbus device.
