### ISSUE TITLE
Unable to adjust focus with GUI

### ISSUE THREAD

**Issue by chibiconsulting** [moof-src/ArduCamFocus#9]
![ArduCamFocus](https://user-images.githubusercontent.com/389921/108949979-409a1880-761a-11eb-8d35-d440c6b871ca.png)
When installing ArduCamFocus (0.0.5) in OctoPrint; there is now a control visible for ArduCam Focus with a value of 100, and two arrows, a disabled one [<] and an enabled one [>] pushing the [>] button generates the following error message.

`2021-02-24 04:35:34,864 - octoprint.plugins.ArduCamFocus - INFO - setting FOCUS to 110
2021-02-24 04:35:34,866 - octoprint.util.comm - ERROR - Error while processing hook ArduCamFocus for phase queuing and command ARDUCAMFOCUS:
Traceback (most recent call last):
  File "/home/pi/oprint/local/lib/python2.7/site-packages/octoprint/util/comm.py", line 4605, in _process_atcommand_phase
    hook(self, phase, atcommand, parameters, tags=tags)
  File "/home/pi/oprint/local/lib/python2.7/site-packages/octoprint/util/__init__.py", line 1890, in wrapper
    return f(*args, **kwargs)
  File "/home/pi/oprint/local/lib/python2.7/site-packages/ArduCamFocus/__init__.py", line 98, in processAtCommand
    self.focus(self.current_focus + int(parameters))
  File "/home/pi/oprint/local/lib/python2.7/site-packages/ArduCamFocus/__init__.py", line 85, in focus
    self.bus.write_byte_data(0xc, data1, data2)
IOError: [Errno 121] Remote I/O error`

What am I missing to figure this out?

**Comment by moof-src** [comment]
probably one of the following:
• you didn’t run the script to enable i2c on your pi
• you don’t have an ArduCam Auto focus camera.  ArduCam sells lots of
cameras.  This one uses I2c to control the focus
• the camera cable may not be seated well in both connectors.

**Comment by chibiconsulting** [comment]
Thank you.
